import CryptoKit
import Foundation
import Testing
@testable import GlassEQLicensing

@Suite
struct EntitlementVerifierTests {
    @Test
    func verifiesTokenIssuedByGoServer() throws {
        // Generated by GlassEQServer's entitlement.Issuer with Ed25519 seed bytes 0x00...0x1f.
        let publicKey = try #require(Data(base64Encoded: "A6EHv/POEL4dcN0Y50vAmWfk1jCbpQ1fHdyGZBJVMbg="))
        let verifier = try EntitlementVerifier(publicKeys: ["go-golden-2026-01": publicKey])
        let token = [
            "eyJhbGciOiJFZERTQSIsImtpZCI6ImdvLWdvbGRlbi0yMDI2LTAxIiwidHlwIjoiZ2xhc3NlcS1lbnRpdGxlbWVudCtqd3QifQ",
            "eyJpc3MiOiJodHRwczovL2xpY2Vuc2UuZ2xhc3NlcS5hcHAiLCJhdWQiOiJjb20uZ2xhc3NlcS5hcHAiLCJzdWIiOiJsaWNfZ29fZ29sZGVuIiwianRpIjoiZW50X2dvX2dvbGRlbiIsImlhdCI6MTgwMDAwMDAwMCwic2NoZW1hIjoxLCJwbGFuIjoibW9udGhseSIsImFjdGl2YXRpb25faWQiOiJhY3RfZ29fZ29sZGVuIiwiaW5zdGFsbGF0aW9uX2lkIjoiNEU3MDYzOEEtM0FCMi00RDIxLUE0QUItMEIyNTI1RjgwRDQyIiwicmV2aXNpb24iOjQyLCJyZWxlYXNlX3Njb3BlIjoiY3VycmVudCIsInNlY3VyaXR5X3VwZGF0ZXNfYWZ0ZXJfZXhwaXJ5Ijp0cnVlLCJiaWxsaW5nX3N0YXRlIjoicmVjb3ZlcmluZyIsImJpbGxpbmdfcGVyaW9kX2VuZCI6MTgwMjU5MjAwMCwicmVjb3ZlcnlfdW50aWwiOjE4MDM4MDE2MDAsInJlZnJlc2hfYWZ0ZXIiOjE4MDA2MDQ4MDAsImV4cCI6MTgwNDQwNjQwMH0",
            "93BRRSor2DKunZhSy1xWOGUO6Flz5etMFbB2y1a9t3gddgr6_10MESnEdaH_xrIJPZE8innnDIRhVJzmMcC_Aw",
        ].joined(separator: ".")

        let entitlement = try verifier.verify(
            token,
            installationID: UUID(uuidString: "4E70638A-3AB2-4D21-A4AB-0B2525F80D42")!,
            highestAcceptedRevision: 41,
            effectiveTime: 1_800_000_000
        )

        #expect(entitlement.claims.licenseID == "lic_go_golden")
        #expect(entitlement.claims.revision == 42)
        #expect(entitlement.claims.monthlyTerms?.billingState == .recovering)
        #expect(entitlement.claims.monthlyTerms?.expiresAt == 1_804_406_400)
    }

    @Test
    func verifiesMonthlyEntitlement() throws {
        let fixture = try EntitlementFixture()
        let token = try fixture.sign(payload: fixture.monthlyPayload())

        let entitlement = try fixture.verifier.verify(
            token,
            installationID: fixture.installationID,
            highestAcceptedRevision: 6,
            effectiveTime: fixture.issuedAt
        )

        #expect(entitlement.keyID == fixture.keyID)
        #expect(entitlement.claims.plan == .monthly)
        #expect(entitlement.claims.monthlyTerms == MonthlyTerms(
            billingState: .active,
            billingPeriodEnd: fixture.billingPeriodEnd,
            recoveryUntil: fixture.recoveryUntil,
            refreshAfter: fixture.refreshAfter,
            expiresAt: fixture.expiresAt
        ))
        #expect(entitlement.claims.revision == 7)
    }

    @Test
    func verifiesPerpetualEntitlement() throws {
        let fixture = try EntitlementFixture()
        let token = try fixture.sign(payload: fixture.perpetualPayload())

        let entitlement = try fixture.verifier.verify(
            token,
            installationID: fixture.installationID,
            highestAcceptedRevision: nil,
            effectiveTime: fixture.issuedAt
        )

        #expect(entitlement.claims.plan == .perpetualV1)
        #expect(entitlement.claims.monthlyTerms == nil)
    }

    @Test
    func rejectsSignatureFromAnotherKey() throws {
        let fixture = try EntitlementFixture()
        let otherKey = Curve25519.Signing.PrivateKey()
        let token = try fixture.sign(payload: fixture.monthlyPayload(), using: otherKey)

        #expect(throws: EntitlementVerificationError.invalidSignature) {
            try fixture.verifier.verify(
                token,
                installationID: fixture.installationID,
                highestAcceptedRevision: nil,
                effectiveTime: fixture.issuedAt
            )
        }
    }

    @Test
    func rejectsUnknownHeaderFields() throws {
        let fixture = try EntitlementFixture()
        let unknownHeader = """
        {"alg":"EdDSA","kid":"\(fixture.keyID)","typ":"glasseq-entitlement+jwt","extra":"value"}
        """

        let unknownToken = try fixture.sign(header: unknownHeader, payload: fixture.monthlyPayload())

        #expect(throws: EntitlementVerificationError.unsupportedHeader) {
            try fixture.verify(unknownToken)
        }
    }

    @Test
    func rejectsUnknownClaims() throws {
        let fixture = try EntitlementFixture()
        let monthlyPayload = fixture.monthlyPayload()
        let unknownPayload = monthlyPayload.dropLast() + ",\"extra\":true}"

        #expect(throws: EntitlementVerificationError.unsupportedClaims) {
            try fixture.verify(try fixture.sign(payload: String(unknownPayload)))
        }
    }

    @Test
    func separatesHeadersAFutureAppMightAcceptFromHeadersNoAppShould() throws {
        let fixture = try EntitlementFixture()
        let payload = fixture.perpetualPayload()

        for invalidHeader in [
            """
            {"alg":"HS256","kid":"\(fixture.keyID)","typ":"glasseq-entitlement+jwt"}
            """,
            """
            {"alg":"EdDSA","kid":"\(fixture.keyID)","typ":"JWT"}
            """,
            """
            {"alg":"EdDSA","kid":"","typ":"glasseq-entitlement+jwt"}
            """
        ] {
            #expect(throws: EntitlementVerificationError.invalidHeader) {
                try fixture.verify(try fixture.sign(header: invalidHeader, payload: payload))
            }
        }

        for malformedPlan in [
            payload.replacingOccurrences(of: "\"plan\":\"perpetual_v1\",", with: ""),
            payload.replacingOccurrences(of: "\"plan\":\"perpetual_v1\"", with: "\"plan\":1")
        ] {
            #expect(throws: EntitlementVerificationError.malformedClaims) {
                try fixture.verify(try fixture.sign(payload: malformedPlan))
            }
        }
    }

    @Test
    func separatesClaimsAFutureAppMightAcceptFromClaimsNoAppShould() throws {
        let fixture = try EntitlementFixture()
        let payload = fixture.perpetualPayload()

        for future in [
            payload.replacingOccurrences(of: "\"schema\":1", with: "\"schema\":2"),
            payload.replacingOccurrences(of: "\"plan\":\"perpetual_v1\"", with: "\"plan\":\"lifetime\""),
            payload.replacingOccurrences(of: "\"release_scope\":\"v1\"", with: "\"release_scope\":\"v2\"")
        ] {
            #expect(throws: EntitlementVerificationError.unsupportedClaims) {
                try fixture.verify(try fixture.sign(payload: future))
            }
        }

        for invalid in [
            payload.replacingOccurrences(of: "https://license.glasseq.app", with: "https://example.com"),
            payload.replacingOccurrences(of: "\"aud\":\"com.glasseq.app\"", with: "\"aud\":\"com.example\""),
            payload.replacingOccurrences(of: fixture.installationID.uuidString, with: "not-a-uuid"),
            payload.replacingOccurrences(of: "\"revision\":7", with: "\"revision\":0"),
            payload.replacingOccurrences(of: "\"sub\":\"lic_01\"", with: "\"sub\":\"\""),
            payload.replacingOccurrences(of: "\"security_updates_after_expiry\":false", with: "\"security_updates_after_expiry\":true")
        ] {
            #expect(throws: EntitlementVerificationError.invalidClaims) {
                try fixture.verify(try fixture.sign(payload: invalid))
            }
        }
    }

    @Test
    func rejectsMismatchedInstallationAndStaleRevision() throws {
        let fixture = try EntitlementFixture()
        let token = try fixture.sign(payload: fixture.monthlyPayload())

        #expect(throws: EntitlementVerificationError.installationMismatch) {
            try fixture.verifier.verify(
                token,
                installationID: UUID(),
                highestAcceptedRevision: nil,
                effectiveTime: fixture.issuedAt
            )
        }
        #expect(throws: EntitlementVerificationError.staleRevision) {
            try fixture.verifier.verify(
                token,
                installationID: fixture.installationID,
                highestAcceptedRevision: 8,
                effectiveTime: fixture.issuedAt
            )
        }
    }

    @Test
    func acceptsFiveMinuteFutureSkewAndRejectsTheNextSecond() throws {
        let fixture = try EntitlementFixture()
        let acceptedToken = try fixture.sign(payload: fixture.monthlyPayload(issuedAt: fixture.issuedAt + 300))
        let rejectedToken = try fixture.sign(payload: fixture.monthlyPayload(issuedAt: fixture.issuedAt + 301))

        _ = try fixture.verify(acceptedToken)
        #expect(throws: EntitlementVerificationError.issuedInFuture) {
            try fixture.verify(rejectedToken)
        }
    }

    @Test
    func rejectsInvalidMonthlyTimeline() throws {
        let fixture = try EntitlementFixture()
        let token = try fixture.sign(payload: fixture.monthlyPayload(expiresAt: fixture.expiresAt + 1))

        #expect(throws: EntitlementVerificationError.invalidTimeline) {
            try fixture.verify(token)
        }
    }

    @Test
    func rejectsPaddedBase64URLAndOversizedToken() throws {
        let fixture = try EntitlementFixture()
        let token = try fixture.sign(payload: fixture.monthlyPayload())
        var parts = token.split(separator: ".", omittingEmptySubsequences: false).map(String.init)
        parts[0] += "="

        #expect(throws: EntitlementVerificationError.invalidBase64URL) {
            try fixture.verify(parts.joined(separator: "."))
        }
        #expect(throws: EntitlementVerificationError.tokenTooLarge) {
            try fixture.verify(String(repeating: "a", count: EntitlementVerifier.maximumTokenBytes + 1))
        }
    }

    @Test
    func rejectsNonIntegralClaims() throws {
        let fixture = try EntitlementFixture()
        let payload = fixture.monthlyPayload().replacingOccurrences(
            of: "\"revision\":7",
            with: "\"revision\":7.5"
        )

        #expect(throws: EntitlementVerificationError.malformedClaims) {
            try fixture.verify(try fixture.sign(payload: payload))
        }
    }
}
